/** Declaration file generated by dts-gen */

export function decode(value: string, fromBase: number | string): number;

export function encode(value: number, toBase: number | string): string;

